/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class activity_songli_com_songlihlcplayer_SongliPlayer */

#ifndef _Included_activity_songli_com_songlihlcplayer_SongliPlayer
#define _Included_activity_songli_com_songlihlcplayer_SongliPlayer



#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     activity_songli_com_songlihlcplayer_SongliPlayer
 * Method:    player
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_activity_songli_com_songlihlcplayer_SongliPlayer_player
  (JNIEnv *, jobject, jstring);




JNIEXPORT void JNICALL Java_activity_songli_com_songlihlcplayer_SongliPlayer_display
        (JNIEnv *, jobject , jobject );
/*
 * Class:     activity_songli_com_songlihlcplayer_SongliPlayer
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_activity_songli_com_songlihlcplayer_SongliPlayer_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
