/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openslse_Activity_SongliPlayer */

#ifndef _Included_com_openslse_Activity_SongliPlayer
#define _Included_com_openslse_Activity_SongliPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openslse_Activity_SongliPlayer
 * Method:    player
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openslse_Activity_SongliPlayer_player
  (JNIEnv *, jobject);

/*
 * Class:     com_openslse_Activity_SongliPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openslse_Activity_SongliPlayer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
